language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

script: 
  - pytest --cov=./

cache:
  directories:
    - node_modules
    - .serverless

after_success:
  - codecov
  - npm install -g serverless
  - serverless deploy

branches:
  only:
    - master