language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

script: 
  - pytest --cov=./

cache:
  directories:
    - node_modules
    - .serverless

after_success:
  - codecov
  - npm install -g serverless
  - if: branch = master
    - env: DEPLOY_STAGE='production'
  - if: branch =~ release/^v\d+\.\d+(\.\d+)?(-\S*)?$/
    - env: DEPLOY_STAGE='beta'
  - if: branch = dev
    - env: DEPLOY_STAGE='dev'
  - serverless deploy --stage $DEPLOY_STAGE

branches:
  only:
    - master
    - release/^v\d+\.\d+(\.\d+)?(-\S*)?$/
    - dev