language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

script: 
  - pytest --cov=./

cache:
  directories:
    - node_modules
    - .serverless

jobs:
  include:
    - if: branch = master
      env: DEPLOY_STAGE=production
    - if: branch =~ /^release\/v\d+\.\d+(\.\d+)?$/
      env: DEPLOY_STAGE=beta
    - if: branch = dev
      env: DEPLOY_STAGE=dev

after_success:
  - codecov
  - npm install -g serverless
  - serverless deploy --stage $DEPLOY_STAGE
